# Absolute root directory for projects.
roots:
    - /www/sites

discovery_filter: '*.dev'

# (optional) - Directory within site folder that is served as the DocumentRoot.
# Can be overridden per-project
public_root: www

# (optional) - Directories to ignore
ignore:
    - ignore.dev

# (optional) - Header navigation links
utils:
    phpmyadmin:
        icon: database
        name: phpMyAdmin
        url: http://phpmyadmin.dev
    github:
        icon: github
        name: Github
        url: https://github.com/your-name
    bitbucket:
        icon: bitbucket
        name: Bitbucket
        url: https://bitbucket.com/your-name

# Project settings
projects:

# Project Template
# ---
#    project_folder:
#        name: ''
#        description: ''
#        public_root: ''
#        links:
#            one:
#                icon: home
#                url: http://google.com
